export const SET_ALL_EVENTS = 'SET_ALL_EVENTS'
export const SET_FILTERED_EVENTS = 'SET_FILTERED_EVENTS'
export const SET_FILTER_DATES_EVENTS = 'SET_FILTER_DATES_EVENTS'
export const START_FETCHING_EVENTS = 'START_FETCHING_EVENTS'
